# codecov:
#   branch: develop

coverage:
  status:
    project:
      default:
        threshold: 0.5

ignore:
  - "docs/"
  - "Notebooks/"
  - "pyIstocsy/runISTOCSY.py"
  - "pyIstocsy/_utilitiesUI.py"