# codecov:
#   branch: develop

coverage:
  status:
    project:
      default:
        threshold: 0.5

ignore:
  - "docs/"
  - "Notebooks/"
  - "pyISTOCSY/runISTOCSY.py"
  - "pyISTOCSY/utilitiesUI.py"