language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

matrix:
  allow_failures:
    - python: "3.7-dev"

branches:
  only:
  - master
  - develop
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # Build releases tagged in the form `v1.2.3`

# command to install dependencies
install:
  - pip install git+git://github.com/PhenomeCentre/pyChemometrics
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

# command to run tests
before_script:
  - cd tests

script:
  - coverage run -m unittest discover

after_success:
  - codecov
  - cd ../

deploy:
  provider: pypi
  user: "phenomecentre"
  password:
    secure: GA4kzsyvaFvxpHlKYmazRjxTjdCJNyCtRrl4eBxoV6hzZP3ZY/MqXJz6fPRP3CKKc7yAB5N4yzOtKYMlmhOI1jgJlstWhTndiOqOsf2BOyA7iXRshjqRy6r7dV8yK3HiTTEgd5ypfSeypH+f5dGgvYaMDka/MXumZypgAo6yp17UoeM1uUqy7hCXMIoYsGBITDtaisWhkpDO1YK4tCIStViqwKP+IZyzo6pHzXzfui93JcEO4UyDDz9P56LtlVV/I8OvsAxQawRKSIcBkIKOgPsV9ItxqNk4q0m41/DXgMLexuvRQo4hASuaWgCcu2kgdOZM00IQlplzbacPZ3vKH7D8JQBWtGssCm7ZDz0RsECUEJHMoojRCv3xcxVZg3KbT77OBr97RE17mMpLvyXDnvbeFPKQmO72lj28Ss5Xj0UMcrCk0WuSM4hJOa3mLFGhp+LtMnu0XajH97Ak8UGSEX3fPcTZ87sOllJbfDcDSjmDY7gMaNyq8laFuFt3qjQjqmcNTWQYOWQvXGtK53YF/S4m0FKTuWinvxZNtiO1XXK0vUs8RBsdsxXsOo3Vew/Mz0uS7UXk7MKCxMCBtCaa+CyhOR36knH5vFvBrBPBy21JyYEuuLjHNkhsbay4dOHScR19LxesuWkOky2wgcaKKcPPZ+RMaoELDxcM42HirD0=
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true
    python: 3.6
